### PR TITLE
Update links for documentation.

### PR DESCRIPTION
**Pull request by DIOHz0r**
## Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: [Conventional Commit](http://conventionalcommits.org/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
No pages displayed in code documentation and coverage for project site.

Related to Issue #22 , Issue #34 

## What is the new behavior?
Pages for code documentation and coverage.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

### CODE REVIEW

**Review by ajsb85 — APPROVED** [review]
Reviewed

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 
All commits message types for gh-pages are "docs"

**Comment by DIOHz0r** [comment]
OK, Fixed the commit type!

**Comment by ajsb85** [comment]
`docs(documentation)` it's redundant, you can use `docs(coverage)`

**Review by ajsb85 — CHANGES_REQUESTED** [review]
`docs(documentation)` is redundant, you can use `docs(coverage)`

**Comment by DIOHz0r** [comment]
The commit not only includes the coverage, it also includes the source documentation, the scope is based on the main menu on the page.

**Comment by ajsb85** [comment]
@DIOHz0r So, use `docs:` and ready or use `docs(*):` then describe more in multiple lines.

**Review by ajsb85 — APPROVED** [review]
Reviewed

**Pull request merged**
