### PR TITLE
Fix documentation section display

### LINKED ISSUE #50: Fix code coverage styles
### Observed Results:
Code coverage style for web site are messed up
  
### Expected behavior:

Page styles according with project branding guides.

### PR DESCRIPTION
**Pull request by Naylin15**
### Changes description
change wrong path to the code documentation
Fix display for coverage
Fix display for code documentation

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### References

Closes #50

### CODE REVIEW

**Comment by Naylin15** [comment]
Update:

This is how it looks now the index

main page

Now working on fixing the tables covered path

Classes

**Comment by Naylin15** [comment]
Tables display

Tables

**Comment by Naylin15** [comment]
Now fixing code documentation display
 How it currently looks

Code documentation

**Comment by Naylin15** [comment]
Update:

The content now follows the correct style

Namespace

Remaining to fix the Documentation dropdown when located in the Code Documentation

**Comment by Naylin15** [comment]
Fixed the dropdown issue following this [Stackoverflow](https://stackoverflow.com/questions/11813304/the-bootstrap-dropdown-open-toggle-does-not-work-properly-in-development-but) 

Dropdown

**Review by ajsb85 — APPROVED** [review]

**Pull request merged**
