### PR TITLE
General client updates

### PR DESCRIPTION
**Pull request by DIOHz0r**
## Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [Conventional Commit](http://conventionalcommits.org/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the new behavior?
Client code updates

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by btry** [comment]
While running unit tests I got an error about JSON not being a valid asserted.

I'm suspecting that this lib is missing in composer (dev section)
https://github.com/atoum/json-schema-extension

Am I right?

**Comment by btry** [comment]
nevermind, the dev dependency is actually declared.

**Review by ajsb85 — APPROVED** [review]
Reviewed

**Comment by DIOHz0r** [comment]
Hi @ajsb85 ,

Please review and merge this changes please.

**Review by ajsb85 — APPROVED** [review]
Reviewed

**Pull request merged**
